# Generated by Django 5.0.7 on 2024-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
