# Generated by Django 5.0.7 on 2024-07-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_monitor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Monitorias',
        ),
    ]
