# Generated by Django 5.0.7 on 2024-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_monitorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
