# Generated by Django 5.0.7 on 2024-07-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_matriculas_remove_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DataUser',
        ),
    ]
