# Generated by Django 5.0.7 on 2024-07-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_horas_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dias'},
        ),
        migrations.AlterModelOptions(
            name='horas',
            options={'verbose_name': 'Hora', 'verbose_name_plural': 'Horas'},
        ),
        migrations.AlterUniqueTogether(
            name='horas',
            unique_together={('day', 'time')},
        ),
    ]
