# Generated by Django 5.0.7 on 2024-07-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_datauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='monitor',
            new_name='staff',
        ),
    ]
