# Generated by Django 5.0.7 on 2024-07-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_days_options_alter_horas_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horas',
            unique_together=set(),
        ),
    ]
