# Generated by Django 5.0.7 on 2024-07-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_monitor_datauser_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula', models.CharField(default='000000000000', max_length=12, primary_key=True, serialize=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.DeleteModel(
            name='Matriculas',
        ),
        migrations.AlterModelOptions(
            name='datauser',
            options={'verbose_name': 'DataUser', 'verbose_name_plural': 'DataUsers'},
        ),
        migrations.AlterModelOptions(
            name='monitorias',
            options={'verbose_name_plural': 'Monitorias'},
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='staff',
        ),
        migrations.AddField(
            model_name='monitorias',
            name='matricula',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='home.matricula'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='matricula',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='monitorias',
            unique_together={('date', 'matricula')},
        ),
    ]
