# Generated by Django 5.0.7 on 2024-07-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_matricula_delete_matriculas_alter_datauser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='matricula',
            field=models.ForeignKey(default=django.db.models.deletion.SET_DEFAULT, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.matricula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(default=django.db.models.deletion.SET_DEFAULT, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitorias',
            name='matricula',
            field=models.ForeignKey(default=django.db.models.deletion.SET_DEFAULT, on_delete=django.db.models.deletion.CASCADE, to='home.matricula'),
        ),
    ]
