# Generated by Django 5.0.7 on 2024-07-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_horas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horas',
            unique_together={('time', 'day')},
        ),
    ]
