# Generated by Django 5.0.7 on 2024-07-17 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_datauser_matricula_alter_matricula_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.matricula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(default='000000000000', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitorias',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.matricula'),
        ),
    ]
