# Generated by Django 5.0.7 on 2024-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_matriculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='matricula',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
