# Generated by Django 5.0.7 on 2024-11-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_datauser_owner_alter_monitorias_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorias',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
